#!/usr/bin/env python3
"""
Company Scraper Pipeline - Main Entry Point

A production-grade automation pipeline that:
1. Reads company names from a CSV file
2. Finds official company websites via Apify Google Search
3. Crawls websites to extract content via Apify Website Content Crawler
4. Generates business descriptions and classifies industries using an LLM
5. Outputs results to an Excel file

Usage:
    python main.py --input companies.csv --output results.xlsx

Environment Variables Required:
    APIFY_API_TOKEN: Your Apify API token
    LLM_API_KEY: Your OpenAI API key (or compatible LLM)

Author: Generated by GitHub Copilot
"""

import argparse
import logging
import sys
import time
from pathlib import Path
from typing import Optional

import pandas as pd
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

from config import Config
from search import CompanySearcher
from crawl import WebsiteCrawler
from summarize import BusinessSummarizer
from utils import setup_logging, validate_csv_schema, batch_items


def parse_arguments() -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="Scrape company information and generate business descriptions",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python main.py --input companies.csv --output results.xlsx
    python main.py --input companies.csv --output results.xlsx --batch-size 50
    python main.py --input companies.csv --output results.xlsx --skip-search
        
Environment Variables:
    APIFY_API_TOKEN    Your Apify API token (required)
    LLM_API_KEY        Your OpenAI/LLM API key (required)
    BATCH_SIZE         Number of companies per batch (default: 30)
    CRAWL_DEPTH        Maximum crawl depth (default: 2)
    MAX_PAGES          Max pages per domain (default: 3)
        """
    )
    
    parser.add_argument(
        "--input", "-i",
        type=str,
        required=True,
        help="Path to input CSV file with company names"
    )
    
    parser.add_argument(
        "--output", "-o",
        type=str,
        required=True,
        help="Path to output Excel file"
    )
    
    parser.add_argument(
        "--batch-size", "-b",
        type=int,
        default=None,
        help="Number of companies per batch (overrides env var)"
    )
    
    parser.add_argument(
        "--skip-search",
        action="store_true",
        help="Skip search step (use if input CSV already has Website column)"
    )
    
    parser.add_argument(
        "--skip-crawl",
        action="store_true",
        help="Skip crawl step (use if input CSV already has Content column)"
    )
    
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable verbose logging"
    )
    
    return parser.parse_args()


def load_input_csv(filepath: str) -> pd.DataFrame:
    """
    Load and validate the input CSV file.
    
    Args:
        filepath: Path to the CSV file
    
    Returns:
        pandas DataFrame with company data
    
    Raises:
        FileNotFoundError: If file doesn't exist
        ValueError: If required columns are missing
    """
    path = Path(filepath)
    if not path.exists():
        raise FileNotFoundError(f"Input file not found: {filepath}")
    
    df = pd.read_csv(filepath)
    validate_csv_schema(df, required_columns=["CompanyName"])
    
    # Clean company names
    df["CompanyName"] = df["CompanyName"].astype(str).str.strip()
    df = df[df["CompanyName"].notna() & (df["CompanyName"] != "")]
    
    return df


def save_results(df: pd.DataFrame, filepath: str) -> None:
    """
    Save results to an Excel file.
    
    Args:
        df: DataFrame with results
        filepath: Output file path
    """
    # Ensure output directory exists
    Path(filepath).parent.mkdir(parents=True, exist_ok=True)
    
    # Save with formatting
    with pd.ExcelWriter(filepath, engine="openpyxl") as writer:
        df.to_excel(writer, index=False, sheet_name="Company Data")
        
        # Auto-adjust column widths
        worksheet = writer.sheets["Company Data"]
        for idx, col in enumerate(df.columns):
            max_length = max(
                df[col].astype(str).apply(len).max(),
                len(col)
            ) + 2
            # Cap column width
            max_length = min(max_length, 80)
            worksheet.column_dimensions[chr(65 + idx)].width = max_length


def process_batch(
    companies: list,
    searcher: CompanySearcher,
    crawler: WebsiteCrawler,
    summarizer: BusinessSummarizer,
    skip_search: bool = False,
    skip_crawl: bool = False,
    existing_data: Optional[dict] = None
) -> list:
    """
    Process a batch of companies through the pipeline.
    
    Args:
        companies: List of company names
        searcher: CompanySearcher instance
        crawler: WebsiteCrawler instance
        summarizer: BusinessSummarizer instance
        skip_search: Skip website search
        skip_crawl: Skip website crawling
        existing_data: Existing data from input CSV
    
    Returns:
        List of result dictionaries
    """
    logger = logging.getLogger("company_scraper")
    results = []
    
    # Step 1: Find websites (or use existing)
    if skip_search and existing_data:
        websites = {c: existing_data.get(c, {}).get("Website") for c in companies}
    else:
        logger.info(f"Searching for {len(companies)} company websites...")
        websites = searcher.search_batch(companies)
    
    # Step 2: Crawl websites (or use existing content)
    if skip_crawl and existing_data:
        contents = {c: existing_data.get(c, {}).get("Content") for c in companies}
    else:
        logger.info(f"Crawling {len([u for u in websites.values() if u])} websites...")
        contents = crawler.crawl_batch(websites)
    
    # Step 3: Summarize with LLM
    logger.info(f"Generating summaries for {len(companies)} companies...")
    summaries = summarizer.summarize_batch(contents)
    
    # Compile results
    for company in companies:
        website = websites.get(company)
        description, category = summaries.get(company, ("Not found", "Other"))
        
        results.append({
            "CompanyName": company,
            "Website": website if website else "Not found",
            "BusinessDescription": description,
            "Category": category
        })
    
    return results


def main():
    """Main entry point for the pipeline."""
    args = parse_arguments()
    
    # Setup logging
    log_level = logging.DEBUG if args.verbose else logging.INFO
    logger = setup_logging(log_level)
    
    logger.info("=" * 60)
    logger.info("Company Scraper Pipeline Starting")
    logger.info("=" * 60)
    
    try:
        # Load configuration
        config = Config.from_env()
        if args.batch_size:
            config.batch_size = args.batch_size
        
        logger.info(f"Batch size: {config.batch_size}")
        logger.info(f"Crawl depth: {config.crawl_depth}")
        logger.info(f"Max pages per domain: {config.max_pages_per_domain}")
        
        # Load input data
        logger.info(f"Loading input file: {args.input}")
        df = load_input_csv(args.input)
        company_names = df["CompanyName"].tolist()
        logger.info(f"Found {len(company_names)} companies to process")
        
        # Check for existing data (for skip modes)
        existing_data = {}
        if args.skip_search and "Website" in df.columns:
            for _, row in df.iterrows():
                existing_data[row["CompanyName"]] = {"Website": row.get("Website")}
        
        # Initialize components
        searcher = CompanySearcher(config)
        crawler = WebsiteCrawler(config)
        summarizer = BusinessSummarizer(config)
        
        # Process in batches
        batches = batch_items(company_names, config.batch_size)
        all_results = []
        
        for i, batch in enumerate(batches):
            logger.info(f"\n{'=' * 40}")
            logger.info(f"Processing batch {i + 1}/{len(batches)} ({len(batch)} companies)")
            logger.info(f"{'=' * 40}")
            
            batch_results = process_batch(
                companies=batch,
                searcher=searcher,
                crawler=crawler,
                summarizer=summarizer,
                skip_search=args.skip_search,
                skip_crawl=args.skip_crawl,
                existing_data=existing_data
            )
            all_results.extend(batch_results)
            
            # Rate limiting between batches
            if i < len(batches) - 1:
                logger.info(f"Waiting {config.request_delay}s before next batch...")
                time.sleep(config.request_delay)
        
        # Save results
        results_df = pd.DataFrame(all_results)
        save_results(results_df, args.output)
        
        logger.info(f"\n{'=' * 60}")
        logger.info(f"Pipeline Complete!")
        logger.info(f"{'=' * 60}")
        logger.info(f"Processed: {len(all_results)} companies")
        logger.info(f"Output saved to: {args.output}")
        
        # Summary statistics
        found = sum(1 for r in all_results if r["Website"] != "Not found")
        logger.info(f"Websites found: {found}/{len(all_results)}")
        
        category_counts = results_df["Category"].value_counts()
        logger.info("\nCategory Distribution:")
        for cat, count in category_counts.items():
            logger.info(f"  {cat}: {count}")
        
    except ValueError as e:
        logger.error(f"Configuration error: {e}")
        sys.exit(1)
    except FileNotFoundError as e:
        logger.error(f"File error: {e}")
        sys.exit(1)
    except Exception as e:
        logger.exception(f"Pipeline failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
